<?php

namespace AppBundle\Entity\Repository;

/**
 * AboutSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
