<?php

namespace AppBundle\Entity\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($term)
    {
        $qb = $this->createQueryBuilder('n');

        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Category', 'a')
            ->where('a.name LIKE :term')
            ->setParameter('term', '%'.$term.'%')

        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
