<?php

namespace AppBundle\Entity\Repository;

/**
 * InfoSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
