<?php

namespace AppBundle\Entity\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($term)
    {
        $qb = $this->createQueryBuilder('n');

        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Product', 'a')
            ->where('a.name LIKE :name')
            ->setParameter('name', '%'.$term.'%')

        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
