<?php

namespace AppBundle\Entity\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function rebateProduct()
    {
        $qb = $this->createQueryBuilder('n');

        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('AppBundle:Product', 'n')
            ->where('n.rebate is not null')


            ->setMaxResults(2)


;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
