#groups:
#      sonata.admin.group.media:
#         label: Media
#        icon:  '<i class="fa fa-file"></i>'
#        items:
#          - config.media.admin
#          - config.gallery.admin

##########school
services:
      admin.school.category:
          class: AppBundle\Admin\CategoryAdmin
          arguments: [~, AppBundle\Entity\Category, ~]
          tags:
              - {
                  name: sonata.admin,
                  manager_type: orm,
                  label:  Категория,
                  group: "Категория",
                  icon: '<i class="fa fa-users"></i>'
                 }
          public: true

      admin.product:
                class: AppBundle\Admin\ProductAdmin
                arguments: [~, AppBundle\Entity\Product, ~]
                tags:
                    - {
                        name: sonata.admin,
                        manager_type: orm,
                        label:  товар,
                        group: "Добавить товар",
                        icon: '<i class="fa fa-users"></i>'
                       }
                public: true

      admin.home.silder:
                class: AppBundle\Admin\HomeSilderAdmin
                arguments: [~, AppBundle\Entity\HomeSlider, ~]
                tags:
                    - {
                        name: sonata.admin,
                        manager_type: orm,
                        label:  Картинки,
                        group: "Главная страница",
                        icon: '<i class="fa fa-users"></i>'
                       }
                public: true



      admin.call.request:
                class: AppBundle\Admin\CallRequestAdmin
                arguments: [~, AppBundle\Entity\CallRequest, ~]
                tags:
                    - {
                        name: sonata.admin,
                        manager_type: orm,
                        label:  Заказать звонок,
                        group: "Заказать звонок",
                        icon: '<i class="fa fa-users"></i>'
                       }
                public: true


      admin.buy:
                class: AppBundle\Admin\BuyAdmin
                arguments: [~, AppBundle\Entity\Buy, ~]
                tags:
                    - {
                        name: sonata.admin,
                        manager_type: orm,
                        label:  заказ продукта,
                        group: "Заказы",
                        icon: '<i class="fa fa-users"></i>'
                       }
                public: true